{{- if include "pg-kv-backend.createPostgresqlSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg-kv-backend.fullname" . }}-postgresql
  labels:
    {{- include "pg-kv-backend.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
