{{- if include "pg-kv-backend.createRedisSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg-kv-backend.fullname" . }}-redis
  labels:
    {{- include "pg-kv-backend.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.redis.password.value | b64enc | quote }}
{{- end }}
