{{- if include "pg-kv-backend.createRedisSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg-kv-backend.redisSecretName" . }}
  labels:
    {{- include "pg-kv-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.redis.password.existingSecret.key | default "redis-password" }}: {{ .Values.redis.password.value | b64enc | quote }}
{{- end }}
