apiVersion: v1
kind: Service
metadata:
  name: {{ include "pg-kv-backend.fullname" . }}
  labels:
    {{- include "pg-kv-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "pg-kv-backend.selectorLabels" . | nindent 4 }}
