replicaCount: 2

redis:
  password:
    value: "demo-password"

postgresql:
  existingSecret:
    name: postkeys-db-app
    usernameKey: username
    passwordKey: password
    portKey: port
    hostKey: host
    databaseKey: dbname
