apiVersion: v2
name: postkeys
description: A Redis-compatible server with PostgreSQL backend
type: application
version: 0.9.0
appVersion: 0.9.1
keywords:
  - redis
  - postgresql
  - key-value
  - cache
maintainers:
  - name: mnorrsken
home: https://github.com/mnorrsken/postkeys
sources:
  - https://github.com/mnorrsken/postkeys
