apiVersion: v2
name: pg-kv-backend
description: A Redis-compatible server with PostgreSQL backend
type: application
version: 0.6.0
appVersion: 0.6.1
keywords:
  - redis
  - postgresql
  - key-value
  - cache
maintainers:
  - name: mnorrsken
home: https://github.com/mnorrsken/pg-kv-backend
sources:
  - https://github.com/mnorrsken/pg-kv-backend
