{{- if include "postkeys.createPostgresqlSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postkeys.fullname" . }}-postgresql
  labels:
    {{- include "postkeys.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
