{{- if include "postkeys.createRedisSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postkeys.redisSecretName" . }}
  labels:
    {{- include "postkeys.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.redis.password.existingSecret.key | default "redis-password" }}: {{ .Values.redis.password.value | b64enc | quote }}
{{- end }}
